//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cake.Plist.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cake.Plist.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!DOCTYPE plist PUBLIC &quot;-//Apple//DTD PLIST 1.0//EN&quot; &quot;http://www.apple.com/DTDs/PropertyList-1.0.dtd&quot;&gt;
        ///&lt;plist version=&quot;1.0&quot;&gt;
        ///&lt;dict&gt;
        ///	&lt;key&gt;CFBundleShortVersionString&lt;/key&gt;
        ///	&lt;string&gt;1.1.3&lt;/string&gt;
        ///	&lt;key&gt;CFBundleVersion&lt;/key&gt;
        ///	&lt;string&gt;1.1.3+Branch.master.Sha.41e4b956b644d0a30e8aa28a6cb6509d99e81031&lt;/string&gt;
        ///	&lt;key&gt;LSRequiresIPhoneOS&lt;/key&gt;
        ///	&lt;true/&gt;
        ///	&lt;key&gt;MinimumOSVersion&lt;/key&gt;
        ///	&lt;string&gt;8.0&lt;/string&gt;
        ///	&lt;key&gt;UIDeviceFamily&lt;/key&gt;
        ///	&lt;array&gt;
        ///		&lt;integer&gt;1&lt;/integer&gt;
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Info_plist {
            get {
                return ResourceManager.GetString("Info_plist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!DOCTYPE plist PUBLIC &quot;-//Apple//DTD PLIST 1.0//EN&quot; &quot;http://www.apple.com/DTDs/PropertyList-1.0.dtd&quot;&gt;
        ///&lt;plist version=&quot;1.0&quot;&gt;
        ///&lt;dict&gt;
        ///	&lt;key&gt;CFBundleShortVersionString&lt;/key&gt;
        ///	&lt;string&gt;1.1.3&lt;/string&gt;
        ///	&lt;key&gt;CFBundleVersion&lt;/key&gt;
        ///	&lt;string&gt;1.1.3+Branch.master.Sha.41e4b956b644d0a30e8aa28a6cb6509d99e81031&lt;/string&gt;
        ///	&lt;key&gt;LSRequiresIPhoneOS&lt;/key&gt;
        ///	&lt;true/&gt;
        ///	&lt;key&gt;MinimumOSVersion&lt;/key&gt;
        ///	&lt;string&gt;8.0&lt;/string&gt;
        ///	&lt;key&gt;UIDeviceFamily&lt;/key&gt;
        ///	&lt;array&gt;
        ///		&lt;integer&gt;1&lt;/integer&gt;
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Issues3_Info_plist {
            get {
                return ResourceManager.GetString("Issues3_Info_plist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;!DOCTYPE plist PUBLIC &quot;-//Apple//DTD PLIST 1.0//EN&quot; &quot;http://www.apple.com/DTDs/PropertyList-1.0.dtd&quot;&gt;
        ///&lt;plist version=&quot;1.0&quot;&gt;
        ///    &lt;dict&gt;
        ///        &lt;key&gt;CFBundleShortVersionString&lt;/key&gt;
        ///        &lt;string&gt;1.1.3&lt;/string&gt;
        ///        &lt;key&gt;CFBundleVersion&lt;/key&gt;
        ///        &lt;string&gt;1.1.3+Branch.master.Sha.41e4b956b644d0a30e8aa28a6cb6509d99e81031&lt;/string&gt;
        ///        &lt;key&gt;LSRequiresIPhoneOS&lt;/key&gt;
        ///        &lt;true /&gt;
        ///        &lt;key&gt;MinimumOSVersion&lt;/key&gt;
        ///        &lt;string&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SerializeResult_plist {
            get {
                return ResourceManager.GetString("SerializeResult_plist", resourceCulture);
            }
        }
    }
}
